build:
  maxIssues: 0

console-reports:
  exclude:
  # - 'ProjectStatisticsReport'
  # - 'ComplexityReport'
  # - 'NotificationReport'
  # - 'FindingsReport'
  # - 'FileBasedFindingsReport'
  # - 'BuildFailureReport'

#complexity:
#  excludes: '**/test/**'
#
#style:
#  excludes: '**/test/**'
