name: build

on: [push]

jobs:
  build:
    name: Full build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: actions/cache@master
        env:
          cache-name: cache-maven-dependencies
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Set up JDK 11
        uses: actions/setup-java@master
        with:
          version: 11

      - name: Build and verify
        run: ./mvnw -C verify

      - name: Create site
        run: ./mvnw -C site
